<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="TransportTests.cs" />
    <Compile Include="..\src\Link\Protocol.cs" Link="Protocol.cs" />
    <Compile Include="..\src\Link\SharedLink.cs" Link="SharedLink.cs" />
  </ItemGroup>
</Project>
